### ISSUE TITLE
Kotlin compiler version needs to be updated

### ISSUE THREAD

**Issue by BlackHornet** [thyrlian/AndroidSDK#11] opened 2018-08-29 07:56 UTC
https://github.com/thyrlian/AndroidSDK/blob/4c9f03e34696026632675a1b51bcfc95a24dda6c/android-sdk/Dockerfile#L33

Please have a look here https://youtrack.jetbrains.com/issue/KT-24946 . 

My docker build failed with reported Exception with the latest of your android-sdk images.

**Comment by BlackHornet** [comment] 2018-08-29 08:09
Downgrading and using thyrlian/android-sdk:2.2 and my project is compilable.

So this is my workaround for now :)

**Comment by thyrlian** [comment] 2018-09-01 13:31
According to the ticket  [KT-24946](https://youtrack.jetbrains.com/issue/KT-24946), the issue should be fixed in build 1.2.60-eap-42.  So I just published a new Docker image `thyrlian/android-sdk:2.4`, which contains [Kotlin compiler 1.2.61](https://github.com/JetBrains/kotlin/releases/tag/v1.2.61).

Could you please give a try and let me know if the issue is solved?  Thanks.

**Closed** 2018-09-04 16:29 UTC
